BNB_BASE_URL = "https://www.bnb.bg/Statistics/StExternalSector/StExchangeRates/StERForeignCurrencies/index.htm?"

BNB_DATE_FORMAT = "%d.%m.%Y"
BNB_SPLIT_BY_MONTHS = 3
BNB_CSV_HEADER_ROWS = 2

NAP_DIGIT_PRECISION = "0.01"
NAP_DATE_FORMAT = "%Y-%m-%d"
NAP_DIVIDEND_TAX = "0.05"

RECEIVED_DIVIDEND_ACTIVITY_TYPES = ["DIV", "DIVCGL", "DIVCGS", "DIVROC", "DIVTXEX"]
TAX_DIVIDEND_ACTIVITY_TYPES = ["DIVNRA", "DIVFT", "DIVTW"]