REVOLUT_DATE_FORMAT = "%m/%d/%Y"
REVOLUT_ACTIVITY_TYPES = ["SELL", "BUY", "DIV", "DIVNRA"]
REVOLUT_CASH_ACTIVITY_TYPES = ["CDEP", "CSD"]
REVOLUT_ACTIVITIES_PAGES_INDICATORS = ["Balance Summary", "ACTIVITY"]
REVOLUT_DIGIT_PRECISION = "0.00000001"

BNB_BASE_URL = "https://www.bnb.bg/Statistics/StExternalSector/StExchangeRates/StERForeignCurrencies/index.htm?"

BNB_DATE_FORMAT = "%d.%m.%Y"
BNB_SPLIT_BY_MONTHS = 3
BNB_CSV_HEADER_ROWS = 2

NAP_DIGIT_PRECISION = "0.01"
NAP_DATE_FORMAT = "%Y-%m-%d"